application:
  applicationName: "review-web"
  space:
    enabled: true
    additionalLabels:
      kind: pr
      team: gabbar
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
    tenant: gabbar

  deployment:
    imagePullSecrets: nexus-docker-config-forked
    additionalLabels:
      appCategory: "frontend"
    additionalPodAnnotations:
      sidecar.istio.io/inject: "true"
      sidecar.istio.io/rewriteAppHTTPProbers: "true"
    podLabels:
      maistra.io/expose-route: "true"
    volumes: {}
    image:
      repository: stakater/nordmart-review-ui
      tag: latest
    env:
    - name: PORT
      value: "4200"
    - name: REVIEW_API
      value: "https://review-gabbar-dev.apps.binero-test.8sdzwd1l.kubeapp.cloud/"
    - name: JAEGER_ENDPOINT
      value: "http://jaeger-collector.istio-system:14268/api/traces"
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 4200
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 4200
  service:
    ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 4200
  rbac:
    create: true
    serviceAccount:
      create: true
      enabled: true
  configMap:
   enabled: false
  route:
    enabled: true
    additionalLabels: 
       router: default
  forecastle:
    enabled: true
    displayName: "Review Web"
    group: "Nordmart"
